#!/usr/bin/env bash
# pgpchat installer
# Usage:  bash install.sh
# Installs the Python dependency and creates a 'pgpchat' launcher in ~/bin/
# (or /usr/local/bin/ if you have write access and prefer a system-wide install).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "==> Installing Python dependency (cryptography) …"
pip install --quiet --break-system-packages -r "$SCRIPT_DIR/requirements.txt" 2>/dev/null \
    || pip install --quiet -r "$SCRIPT_DIR/requirements.txt"

echo "==> Making pgpchat.py executable …"
chmod +x "$SCRIPT_DIR/pgpchat.py"

# Decide install location
INSTALL_DIR="$HOME/bin"
if [[ -w /usr/local/bin ]]; then
    read -rp "Install system-wide to /usr/local/bin? [y/N] " yn
    if [[ "$yn" =~ ^[Yy]$ ]]; then
        INSTALL_DIR="/usr/local/bin"
    fi
fi

mkdir -p "$INSTALL_DIR"

WRAPPER="$INSTALL_DIR/pgpchat"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# pgpchat wrapper — generated by install.sh
PYTHONPATH="$SCRIPT_DIR" exec python3 "$SCRIPT_DIR/pgpchat.py" "\$@"
EOF
chmod +x "$WRAPPER"

echo ""
echo "✓ pgpchat installed to: $WRAPPER"

# Check if INSTALL_DIR is on PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo ""
    echo "  Note: $INSTALL_DIR is not in your PATH."
    echo "  Add this to your shell config (~/.bashrc / ~/.zshrc):"
    echo "    export PATH=\"\$HOME/bin:\$PATH\""
fi

echo ""
echo "Quick start:"
echo "  pgpchat keygen          # generate your key pair"
echo "  pgpchat whoami          # show your public key to share"
echo "  pgpchat import <name>   # import a contact's public key"
echo "  pgpchat listen          # wait for a connection on port 7890"
echo "  pgpchat connect <name> <host>   # connect to a contact"
